[project]
name = "api_autenticacao"
version = "0.1.0"
description = "API de autenticação de usuários para portfólio"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "passlib[bcrypt]",
    "python-jose[cryptography]",
    "SQLAlchemy",
    "psycopg2-binary",
]