name: ci-cd.yml
on:
  push:
    branches:
      - dev

jobs:
   build:

    environment:  API

    runs-on: ubuntu-latest

    steps:
      - name: clone do repositorio
        uses: actions/checkout@v5

      - name: Configurar docker
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Deploy da imagem no docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: kbrum/api-dockerfiles:latest
