name: workflow.yml
on:
  push:
    branches:
      - dev

jobs:
   build:

    runs-on: ubuntu-latest

    steps:
      - name: clone do repositorio
        uses: actions/checkout@v4

      - name: Configurar docker
        uses: docker/setup-buildx-action@v3

      - name: Construir imagem Docker
        run: |
          docker build -t crm:backend -f backend/Dockerfile backend

          

